export const SUPER_ADMIN_USER_MANAGEMENT_PAGE = 'SUPER_ADMIN_USER_MANAGEMENT_PAGE';
export const SUPER_ADMIN_ORGANIZATIONS_MANAGEMENT_PAGE = 'SUPER_ADMIN_ORGANIZATIONS_MANAGEMENT_PAGE';
export const ORGANIZATION_INVITATION_PAGE = 'ORGANIZATION_INVITATION_PAGE';
export const HAS_LOGIN = 'HAS_LOGIN';
