export const HAS_LOGIN = 'HAS_LOGIN';

export const SUPER_ADMIN_ACCESS = 'SUPER_ADMIN_ACCESS';
export const SUPER_ADMIN_USER_MANAGEMENT_PAGE = 'SUPER_ADMIN_USER_MANAGEMENT_PAGE';
export const SUPER_ADMIN_ORGANIZATIONS_MANAGEMENT_PAGE =
    'SUPER_ADMIN_ORGANIZATIONS_MANAGEMENT_PAGE';
export const SUPER_ADMIN_SERVICE_CATEGORIES_MANAGEMENT_PAGE =
    'SUPER_ADMIN_SERVICE_CATEGORIES_MANAGEMENT_PAGE';
export const ORGANIZATION_MANAGEMENT_PAGE = 'ORGANIZATION_MANAGEMENT_PAGE';
export const USER_ROOMS_PAGE = 'USER_ROOMS_PAGE';
export const USER_DASHBOARD_PAGE = 'USER_DASHBOARD_PAGE';
export const USER_SERVICES_PAGE = 'USER_SERVICES_PAGE';
export const USER_APPOINTMENTS_PAGE = 'USER_APPOINTMENTS_PAGE';
export const USER_INVITATIONS_PAGE = 'USER_INVITATIONS_PAGE';
export const USER_FAVOURITES_PAGE = 'USER_FAVOURITES_PAGE';
export const USER_REVIEWS_PAGE = 'USER_REVIEWS_PAGE';
export const USER_PROFILE_PAGE = 'USER_PROFILE_PAGE';
export const USER_SETTINGS_PAGE = 'USER_SETTINGS_PAGE';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const VIEW_OWN_APPOINTMENTS = 'VIEW_OWN_APPOINTMENTS';
export const UPDATE_OWN_APPOINTMENT = 'UPDATE_OWN_APPOINTMENT';
export const CANCEL_OWN_APPOINTMENT = 'CANCEL_OWN_APPOINTMENT';

export const VIEW_FAVOURITES = 'VIEW_FAVOURITES';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';

export const VIEW_REVIEWS = 'VIEW_REVIEWS';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const UPDATE_OWN_REVIEW = 'UPDATE_OWN_REVIEW';
export const DELETE_OWN_REVIEW = 'DELETE_OWN_REVIEW';

export const ORGANIZATION_INVITATION_PAGE = 'ORGANIZATION_INVITATION_PAGE';
export const VIEW_OWN_INVITATIONS = 'VIEW_OWN_INVITATIONS';
export const ACCEPT_ORGANIZATION_INVITATION = 'ACCEPT_ORGANIZATION_INVITATION';
export const REJECT_ORGANIZATION_INVITATION = 'REJECT_ORGANIZATION_INVITATION';

export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';

export const CREATE_SERVICE = 'CREATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';

export const CREATE_ROOM = 'CREATE_ROOM';
export const UPDATE_ROOM = 'UPDATE_ROOM';

export const READ_ORGANIZATION_INVITATIONS = 'READ_ORGANIZATION_INVITATIONS';
export const CREATE_ORGANIZATION_INVITATIONS = 'CREATE_ORGANIZATION_INVITATIONS';

export const READ_USERS = 'READ_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER_AS_ADMIN = 'UPDATE_USER_AS_ADMIN';

export const UPDATE_ORGANIZATION_AS_ADMIN = 'UPDATE_ORGANIZATION_AS_ADMIN';
export const CREATE_SERVICE_CATEGORY = 'CREATE_SERVICE_CATEGORY';
